import { db } from "./SQLite";

export function writeBelTable() {
  stickers = [
    1,
    "Squad",
    "BEL-1",
    0,
    2,
    "Logo",
    "BEL-2",
    0,
    3,
    "Thibaut Courtois",
    "BEL-3",
    0,
    4,
    "Simon Mignolet",
    "BEL-4",
    0,
    5,
    "Toby Alderweireld",
    "BEL-5",
    0,
    6,
    "Timothy Castagne",
    "BEL-6",
    0,
    7,
    "Jason Denayer",
    "BEL-7",
    0,
    8,
    "Thomas Meunier",
    "BEL-8",
    0,
    9,
    "Jan Vertonghen",
    "BEL-9",
    0,
    10,
    "Yannick Carrasco",
    "BEL-10",
    0,
    11,
    "Kevin De Bruyne",
    "BEL-11",
    0,
    12,
    "Charles De Ketelaere",
    "BEL-12",
    0,
    13,
    "Thorgan Hazard",
    "BEL-13",
    0,
    14,
    "Youri Tielemans",
    "BEL-14",
    0,
    15,
    "Hans Vanaken",
    "BEL-15",
    0,
    16,
    "Axel Witsel",
    "BEL-16",
    0,
    17,
    "Jérémy Doku",
    "BEL-17",
    0,
    18,
    "Eden Hazard",
    "BEL-18",
    0,
    19,
    "Romelu Lukaku",
    "BEL-19",
    0,
    20,
    "Dries Mertens",
    "BEL-20",
    0,
  ];

  return addMultipleLines("BEL", stickers);
}

export function writeCrcTable() {
  stickers = [
    1,
    "Squad",
    "CRC-1",
    0,
    2,
    "Logo",
    "CRC-2",
    0,
    3,
    "Keylor Navas",
    "CRC-3",
    0,
    4,
    "Leonel Moreira",
    "CRC-4",
    0,
    5,
    "Ricardo Blanco",
    "CRC-5",
    0,
    6,
    "Francisco Calvo",
    "CRC-6",
    0,
    7,
    "Óscar Duarte",
    "CRC-7",
    0,
    8,
    "Keysher Fuller",
    "CRC-8",
    0,
    9,
    "Bryan Oviedo",
    "CRC-9",
    0,
    10,
    "Juan Pablo Vargas",
    "CRC-10",
    0,
    11,
    "Kendall Waston",
    "CRC-11",
    0,
    12,
    "Celso Borges",
    "CRC-12",
    0,
    13,
    "Orlando Galo",
    "CRC-13",
    0,
    14,
    "Bryan Ruiz",
    "CRC-14",
    0,
    15,
    "Yeltsin Tejeda",
    "CRC-15",
    0,
    16,
    "Jewison Bennette",
    "CRC-16",
    0,
    17,
    "Joel Campbell",
    "CRC-17",
    0,
    18,
    "Anthony Contreras",
    "CRC-18",
    0,
    19,
    "Gerson Torres",
    "CRC-19",
    0,
    20,
    "Johan Venegas",
    "CRC-20",
    0,
  ];

  return addMultipleLines("CRC", stickers);
}

export function writeJpnTable() {
  stickers = [
    1,
    "Squad",
    "JPN-1",
    0,
    2,
    "Logo",
    "JPN-2",
    0,
    3,
    "Shuichi Gonda",
    "JPN-3",
    0,
    4,
    "Eiji Kawashima",
    "JPN-4",
    0,
    5,
    "Yuto Nagatomo",
    "JPN-5",
    0,
    6,
    "Yuta Nakayama",
    "JPN-6",
    0,
    7,
    "Takehiro Tomiyasu",
    "JPN-7",
    0,
    8,
    "Miki Yamane",
    "JPN-8",
    0,
    9,
    "Maya Yoshida",
    "JPN-9",
    0,
    10,
    "Wataru Endo",
    "JPN-10",
    0,
    11,
    "Genki Haraguchi",
    "JPN-11",
    0,
    12,
    "Hidemasa Morita",
    "JPN-12",
    0,
    13,
    "Gaku Shibasaki",
    "JPN-13",
    0,
    14,
    "Ao Tanaka",
    "JPN-14",
    0,
    15,
    "Takuma Asano",
    "JPN-15",
    0,
    16,
    "Kyogo Furuhashi",
    "JPN-16",
    0,
    17,
    "Junya Ito",
    "JPN-17",
    0,
    18,
    "Takumi Minamino",
    "JPN-18",
    0,
    19,
    "Kaoru Mitoma",
    "JPN-19",
    0,
    20,
    "Yuya Osako",
    "JPN-20",
    0,
  ];

  return addMultipleLines("JPN", stickers);
}

export function writeNedTable() {
  stickers = [
    1,
    "Squad",
    "NED-1",
    0,
    2,
    "Logo",
    "NED-2",
    0,
    3,
    "Justin Bijlow",
    "NED-3",
    0,
    4,
    "Jasper Cillessen",
    "NED-4",
    0,
    5,
    "Daley Blind",
    "NED-5",
    0,
    6,
    "Matthijs de Ligt",
    "NED-6",
    0,
    7,
    "Stefan de Vrij",
    "NED-7",
    0,
    8,
    "Denzel Dumfries",
    "NED-8",
    0,
    9,
    "Virgil van Dijk",
    "NED-9",
    0,
    10,
    "Steven Berghuis",
    "NED-10",
    0,
    11,
    "Frenkie de Jong",
    "NED-11",
    0,
    12,
    "Ryan Gravenberch",
    "NED-12",
    0,
    13,
    "Davy Klaassen",
    "NED-13",
    0,
    14,
    "Teun Koopmeiners",
    "NED-14",
    0,
    15,
    "Georginio Wijnaldum",
    "NED-15",
    0,
    16,
    "Steven Bergwijn",
    "NED-16",
    0,
    17,
    "Arnaut Danjuma",
    "NED-17",
    0,
    18,
    "Memphis Depay",
    "NED-18",
    0,
    19,
    "Cody Gakpo",
    "NED-19",
    0,
    20,
    "Donyell Malen",
    "NED-20",
    0,
  ];

  return addMultipleLines("NED", stickers);
}

export function writePorTable() {
  stickers = [
    1,
    "Squad",
    "POR-1",
    0,
    2,
    "Logo",
    "POR-2",
    0,
    3,
    "Diogo Costa",
    "POR-3",
    0,
    4,
    "Rui Patrício",
    "POR-4",
    0,
    5,
    "João Cancelo",
    "POR-5",
    0,
    6,
    "José Fonte",
    "POR-6",
    0,
    7,
    "Nuno Mendes",
    "POR-7",
    0,
    8,
    "Pepe",
    "POR-8",
    0,
    9,
    "Raphaël Guerreiro",
    "POR-9",
    0,
    10,
    "Rúben Dias",
    "POR-10",
    0,
    11,
    "Bernardo Silva",
    "POR-11",
    0,
    12,
    "Bruno Fernandes",
    "POR-12",
    0,
    13,
    "Danilo Pereira",
    "POR-13",
    0,
    14,
    "João Moutinho",
    "POR-14",
    0,
    15,
    "Renato Sanches",
    "POR-15",
    0,
    16,
    "Rúben Neves",
    "POR-16",
    0,
    17,
    "André Silva ",
    "POR-17",
    0,
    18,
    "Cristiano Ronaldo",
    "POR-18",
    0,
    19,
    "Diogo Jota",
    "POR-19",
    0,
    20,
    "Gonçalo Guedes",
    "POR-20",
    0,
  ];

  return addMultipleLines("POR", stickers);
}

export function writeSenTable() {
  stickers = [
    1,
    "Squad",
    "SEN-1",
    0,
    2,
    "Logo",
    "SEN-2",
    0,
    3,
    "Édouard Mendy",
    "SEN-3",
    0,
    4,
    "Alfred Gomis",
    "SEN-4",
    0,
    5,
    "Saliou Ciss",
    "SEN-5",
    0,
    6,
    "Pape Abou Cissé",
    "SEN-6",
    0,
    7,
    "Abdou Diallo",
    "SEN-7",
    0,
    8,
    "Kalidou Koulibaly",
    "SEN-8",
    0,
    9,
    "Ibrahima Mbaye",
    "SEN-9",
    0,
    10,
    "Bouna Sarr",
    "SEN-10",
    0,
    11,
    "Krépin Diatta",
    "SEN-11",
    0,
    12,
    "Idrissa Gueye",
    "SEN-12",
    0,
    13,
    "Pape Gueye",
    "SEN-13",
    0,
    14,
    "Cheikhou Kouyaté",
    "SEN-14",
    0,
    15,
    "Nampalys Mendy",
    "SEN-15",
    0,
    16,
    "Boulaye Dia",
    "SEN-16",
    0,
    17,
    "Famara Diédhiou ",
    "SEN-17",
    0,
    18,
    "Bamba Dieng",
    "SEN-18",
    0,
    19,
    "Sadio Mané",
    "SEN-19",
    0,
    20,
    "Ismaïla Sarr",
    "SEN-20",
    0,
  ];

  return addMultipleLines("SEN", stickers);
}

export function createTables() {
  listCountries = ["BEL", "CRC", "JPN", "NED", "POR", "SEN"];
  listCountries.forEach((country) => {
    db.transaction((transaction) => {
      transaction.executeSql(
        "CREATE TABLE IF NOT EXISTS " +
          country +
          " (id INTEGER PRIMARY KEY AUTOINCREMENT, number INTEGER, name TEXT, cod TEXT, hasSticker INTEGER);"
      );
    });
  });
}

export async function markAsUnavailable(codeList) {
  codeList.forEach((code) => {
    country = code.split("-");
    db.transaction((transaction) => {
      transaction.executeSql(
        "UPDATE " + country[0] + " SET hasSticker = ? WERE cod = ?;",
        [1, code],
        (transaction, resultado) => {
          resolve(resultado.rows._array);
        }
      );
    });
  });
}

async function readCountry(country) {
  return new Promise((resolve) => {
    db.transaction((transaction) => {
      transaction.executeSql(
        "SELECT name, cod, hasSticker FROM " +
          country +
          " WHERE number=" +
          parseInt(number) +
          ";",
        [],
        (transaction, resultado) => {
          resolve(resultado.rows._array);
        }
      );
    });
  });
}

export async function readAll() {
  listCountries = ["BEL", "CRC", "JPN", "NED", "POR", "SEN"];
  stickersList = [];
  for (let i = 0; i < listCountries.lenght; i++) {
    list = await readCountry(listCountries[i]);
    stickersList.concat(list);
  }

  return stickersList;
}

function addMultipleLines(table, stickers) {
  query = "INSERT INTO " + table + " VALUES(?, ?, ?, ?)";
  for (let i = 0; i < sticker.lenght; i++) {
    query = query + ", (?, ?, ?, ?)";
  }
  query = query + ";";

  return new Promise((resolve) => {
    db.transaction((transaction) => {
      transaction.executeSql(query, stickers, (transaction, resultado) => {
        resolve("deu tudo certo");
      });
    });
  });
}

export function getData() {
  data = [
    {
      name: "Squad",
      cod: "BEL-1",
      hasSticker: 0,
      image: require("../../assets/db/BEL-1.jpg"),
    },
    {
      name: "Logo",
      cod: "BEL-2",
      hasSticker: 0,
      image: require("../../assets/db/BEL-2.jpg"),
    },
    {
      name: "Thibaut Courtois",
      cod: "BEL-3",
      hasSticker: 0,
      image: require("../../assets/db/BEL-3.jpg"),
    },
    {
      name: "Simon Mignolet",
      cod: "BEL-4",
      hasSticker: 0,
      image: require("../../assets/db/BEL-4.jpg"),
    },
    {
      name: "Toby Alderweireld",
      cod: "BEL-5",
      hasSticker: 0,
      image: require("../../assets/db/BEL-5.jpg"),
    },
    {
      name: "Timothy Castagne",
      cod: "BEL-6",
      hasSticker: 0,
      image: require("../../assets/db/BEL-6.jpg"),
    },
    {
      name: "Jason Denayer",
      cod: "BEL-7",
      hasSticker: 0,
      image: require("../../assets/db/BEL-7.jpg"),
    },
    {
      name: "Thomas Meunier",
      cod: "BEL-8",
      hasSticker: 0,
      image: require("../../assets/db/BEL-8.jpg"),
    },
    {
      name: "Jan Vertonghen",
      cod: "BEL-9",
      hasSticker: 0,
      image: require("../../assets/db/BEL-9.jpg"),
    },
    {
      name: "Yannick Carrasco",
      cod: "BEL-10",
      hasSticker: 0,
      image: require("../../assets/db/BEL-10.jpg"),
    },
    {
      name: "Kevin De Bruyne",
      cod: "BEL-11",
      hasSticker: 0,
      image: require("../../assets/db/BEL-11.jpg"),
    },
    {
      name: "Charles De Ketelaere",
      cod: "BEL-12",
      hasSticker: 0,
      image: require("../../assets/db/BEL-12.jpg"),
    },
    {
      name: "Thorgan Hazard",
      cod: "BEL-13",
      hasSticker: 0,
      image: require("../../assets/db/BEL-13.jpg"),
    },
    {
      name: "Youri Tielemans",
      cod: "BEL-14",
      hasSticker: 0,
      image: require("../../assets/db/BEL-14.jpg"),
    },
    {
      name: "Hans Vanaken",
      cod: "BEL-15",
      hasSticker: 0,
      image: require("../../assets/db/BEL-15.jpg"),
    },
    {
      name: "Axel Witsel",
      cod: "BEL-16",
      hasSticker: 0,
      image: require("../../assets/db/BEL-16.jpg"),
    },
    {
      name: "Jérémy Doku",
      cod: "BEL-17",
      hasSticker: 0,
      image: require("../../assets/db/BEL-17.jpg"),
    },
    {
      name: "Eden Hazard",
      cod: "BEL-18",
      hasSticker: 0,
      image: require("../../assets/db/BEL-18.jpg"),
    },
    {
      name: "Romelu Lukaku",
      cod: "BEL-19",
      hasSticker: 0,
      image: require("../../assets/db/BEL-19.jpg"),
    },
    {
      name: "Dries Mertens",
      cod: "BEL-20",
      hasSticker: 0,
      image: require("../../assets/db/BEL-20.jpg"),
    },
    {
      name: "Squad",
      cod: "CRC-1",
      ",hasSticker": 0,
      image: require("../../assets/db/CRC-1.jpg"),
    },
    {
      name: "Logo",
      cod: "CRC-2",
      hasSticker: 0,
      image: require("../../assets/db/CRC-2.jpg"),
    },
    {
      name: "Keylor Navas",
      cod: "CRC-3",
      hasSticker: 0,
      image: require("../../assets/db/CRC-3.jpg"),
    },
    {
      name: "Leonel Moreira",
      cod: "CRC-4",
      hasSticker: 0,
      image: require("../../assets/db/CRC-4.jpg"),
    },
    {
      name: "Ricardo Blanco",
      cod: "CRC-5",
      hasSticker: 0,
      image: require("../../assets/db/CRC-5.jpg"),
    },
    {
      name: "Francisco Calvo",
      cod: "CRC-6",
      hasSticker: 0,
      image: require("../../assets/db/CRC-6.jpg"),
    },
    {
      name: "Óscar Duarte",
      cod: "CRC-7",
      hasSticker: 0,
      image: require("../../assets/db/CRC-7.jpg"),
    },
    {
      name: "Keysher Fuller",
      cod: "CRC-8",
      hasSticker: 0,
      image: require("../../assets/db/CRC-8.jpg"),
    },
    {
      name: "Bryan Oviedo",
      cod: "CRC-9",
      hasSticker: 0,
      image: require("../../assets/db/CRC-9.jpg"),
    },
    {
      name: "Juan Pablo Vargas",
      cod: "CRC-10",
      hasSticker: 0,
      image: require("../../assets/db/CRC-10.jpg"),
    },
    {
      name: "Kendall Waston",
      cod: "CRC-11",
      hasSticker: 0,
      image: require("../../assets/db/CRC-11.jpg"),
    },
    {
      name: "Celso Borges",
      cod: "CRC-12",
      hasSticker: 0,
      image: require("../../assets/db/CRC-12.jpg"),
    },
    {
      name: "Orlando Galo",
      cod: "CRC-13",
      hasSticker: 0,
      image: require("../../assets/db/CRC-13.jpg"),
    },
    {
      name: "Bryan Ruiz",
      cod: "CRC-14",
      hasSticker: 0,
      image: require("../../assets/db/CRC-14.jpg"),
    },
    {
      name: "Yeltsin Tejeda",
      cod: "CRC-15",
      hasSticker: 0,
      image: require("../../assets/db/CRC-15.jpg"),
    },
    {
      name: "Jewison Bennette",
      cod: "CRC-16",
      hasSticker: 0,
      image: require("../../assets/db/CRC-16.jpg"),
    },
    {
      name: "Joel Campbell",
      cod: "CRC-17",
      hasSticker: 0,
      image: require("../../assets/db/CRC-17.jpg"),
    },
    {
      name: "Anthony Contreras",
      cod: "CRC-18",
      hasSticker: 0,
      image: require("../../assets/db/CRC-18.jpg"),
    },
    {
      name: "Gerson Torres",
      cod: "CRC-19",
      hasSticker: 0,
      image: require("../../assets/db/CRC-19.jpg"),
    },
    {
      name: "Johan Venegas",
      cod: "CRC-20",
      hasSticker: 0,
      image: require("../../assets/db/CRC-20.jpg"),
    },
    {
      name: "Squad",
      cod: "JPN-1",
      hasSticker: 0,
      image: require("../../assets/db/JPN-1.jpg"),
    },
    {
      name: "Logo",
      cod: "JPN-2",
      hasSticker: 0,
      image: require("../../assets/db/JPN-2.jpg"),
    },
    {
      name: "Shuichi Gonda",
      cod: "JPN-3",
      hasSticker: 0,
      image: require("../../assets/db/JPN-3.jpg"),
    },
    {
      name: "Eiji Kawashima",
      cod: "JPN-4",
      hasSticker: 0,
      image: require("../../assets/db/JPN-4.jpg"),
    },
    {
      name: "Yuto Nagatomo",
      cod: "JPN-5",
      hasSticker: 0,
      image: require("../../assets/db/JPN-5.jpg"),
    },
    {
      name: "Yuta Nakayama",
      cod: "JPN-6",
      hasSticker: 0,
      image: require("../../assets/db/JPN-6.jpg"),
    },
    {
      name: "Takehiro Tomiyasu",
      cod: "JPN-7",
      hasSticker: 0,
      image: require("../../assets/db/JPN-7.jpg"),
    },
    {
      name: "Miki Yamane",
      cod: "JPN-8",
      hasSticker: 0,
      image: require("../../assets/db/JPN-8.jpg"),
    },
    {
      name: "Maya Yoshida",
      cod: "JPN-9",
      hasSticker: 0,
      image: require("../../assets/db/JPN-9.jpg"),
    },
    {
      name: "Wataru Endo",
      cod: "JPN-10",
      hasSticker: 0,
      image: require("../../assets/db/JPN-10.jpg"),
    },
    {
      name: "Genki Haraguchi",
      cod: "JPN-11",
      hasSticker: 0,
      image: require("../../assets/db/JPN-11.jpg"),
    },
    {
      name: "Hidemasa Morita",
      cod: "JPN-12",
      hasSticker: 0,
      image: require("../../assets/db/JPN-12.jpg"),
    },
    {
      name: "Gaku Shibasaki",
      cod: "JPN-13",
      hasSticker: 0,
      image: require("../../assets/db/JPN-13.jpg"),
    },
    {
      name: "Ao Tanaka",
      cod: "JPN-14",
      hasSticker: 0,
      image: require("../../assets/db/JPN-14.jpg"),
    },
    {
      name: "Takuma Asano",
      cod: "JPN-15",
      hasSticker: 0,
      image: require("../../assets/db/JPN-15.jpg"),
    },
    {
      name: "Kyogo Furuhashi",
      cod: "JPN-16",
      hasSticker: 0,
      image: require("../../assets/db/JPN-16.jpg"),
    },
    {
      name: "Junya Ito",
      cod: "JPN-17",
      hasSticker: 0,
      image: require("../../assets/db/JPN-17.jpg"),
    },
    {
      name: "Takumi Minamino",
      cod: "JPN-18",
      hasSticker: 0,
      image: require("../../assets/db/JPN-18.jpg"),
    },
    {
      name: "Kaoru Mitoma",
      cod: "JPN-19",
      hasSticker: 0,
      image: require("../../assets/db/JPN-19.jpg"),
    },
    {
      name: "Yuya Osako",
      cod: "JPN-20",
      hasSticker: 0,
      image: require("../../assets/db/JPN-20.jpg"),
    },
    {
      name: "Squad",
      cod: "NED-1",
      hasSticker: 0,
      image: require("../../assets/db/NED-1.jpg"),
    },
    {
      name: "Logo",
      cod: "NED-2",
      hasSticker: 0,
      image: require("../../assets/db/NED-2.jpg"),
    },
    {
      name: "Justin Bijlow",
      cod: "NED-3",
      hasSticker: 0,
      image: require("../../assets/db/NED-3.jpg"),
    },
    {
      name: "Jasper Cillessen",
      cod: "NED-4",
      hasSticker: 0,
      image: require("../../assets/db/NED-4.jpg"),
    },
    {
      name: "Daley Blind",
      cod: "NED-5",
      hasSticker: 0,
      image: require("../../assets/db/NED-5.jpg"),
    },
    {
      name: "Matthijs de Ligt",
      cod: "NED-6",
      hasSticker: 0,
      image: require("../../assets/db/NED-6.jpg"),
    },
    {
      name: "Stefan de Vrij",
      cod: "NED-7",
      hasSticker: 0,
      image: require("../../assets/db/NED-7.jpg"),
    },
    {
      name: "Denzel Dumfries",
      cod: "NED-8",
      hasSticker: 0,
      image: require("../../assets/db/NED-8.jpg"),
    },
    {
      name: "Virgil van Dijk",
      cod: "NED-9",
      hasSticker: 0,
      image: require("../../assets/db/NED-9.jpg"),
    },
    {
      name: "Steven Berghuis",
      cod: "NED-10",
      hasSticker: 0,
      image: require("../../assets/db/NED-10.jpg"),
    },
    {
      name: "Frenkie de Jong",
      cod: "NED-11",
      hasSticker: 0,
      image: require("../../assets/db/NED-11.jpg"),
    },
    {
      name: "Ryan Gravenberch",
      cod: "NED-12",
      hasSticker: 0,
      image: require("../../assets/db/NED-12.jpg"),
    },
    {
      name: "Davy Klaassen",
      cod: "NED-13",
      hasSticker: 0,
      image: require("../../assets/db/NED-13.jpg"),
    },
    {
      name: "Teun Koopmeiners",
      cod: "NED-14",
      hasSticker: 0,
      image: require("../../assets/db/NED-14.jpg"),
    },
    {
      name: "Georginio Wijnaldum",
      cod: "NED-15",
      hasSticker: 0,
      image: require("../../assets/db/NED-15.jpg"),
    },
    {
      name: "Steven Bergwijn",
      cod: "NED-16",
      hasSticker: 0,
      image: require("../../assets/db/NED-16.jpg"),
    },
    {
      name: "Arnaut Danjuma",
      cod: "NED-17",
      hasSticker: 0,
      image: require("../../assets/db/NED-17.jpg"),
    },
    {
      name: "Memphis Depay",
      cod: "NED-18",
      hasSticker: 0,
      image: require("../../assets/db/NED-18.jpg"),
    },
    {
      name: "Cody Gakpo",
      cod: "NED-19",
      hasSticker: 0,
      image: require("../../assets/db/NED-19.jpg"),
    },
    {
      name: "Donyell Malen",
      cod: "NED-20",
      hasSticker: 0,
      image: require("../../assets/db/NED-20.jpg"),
    },
    {
      name: "Squad",
      cod: "POR-1",
      hasSticker: 0,
      image: require("../../assets/db/POR-1.jpg"),
    },
    {
      name: "Logo",
      cod: "POR-2",
      hasSticker: 0,
      image: require("../../assets/db/POR-2.jpg"),
    },
    {
      name: "Diogo Costa",
      cod: "POR-3",
      hasSticker: 0,
      image: require("../../assets/db/POR-3.jpg"),
    },
    {
      name: "Rui Patrício",
      cod: "POR-4",
      hasSticker: 0,
      image: require("../../assets/db/POR-4.jpg"),
    },
    {
      name: "João Cancelo",
      cod: "POR-5",
      hasSticker: 0,
      image: require("../../assets/db/POR-5.jpg"),
    },
    {
      name: "José Fonte",
      cod: "POR-6",
      hasSticker: 0,
      image: require("../../assets/db/POR-6.jpg"),
    },
    {
      name: "Nuno Mendes",
      cod: "POR-7",
      hasSticker: 0,
      image: require("../../assets/db/POR-7.jpg"),
    },
    {
      name: "Pepe",
      cod: "POR-8",
      hasSticker: 0,
      image: require("../../assets/db/POR-8.jpg"),
    },
    {
      name: "Raphaël Guerreiro",
      cod: "POR-9",
      hasSticker: 0,
      image: require("../../assets/db/POR-9.jpg"),
    },
    {
      name: "Rúben Dias",
      cod: "POR-10",
      hasSticker: 0,
      image: require("../../assets/db/POR-10.jpg"),
    },
    {
      name: "Bernardo Silva",
      cod: "POR-11",
      hasSticker: 0,
      image: require("../../assets/db/POR-11.jpg"),
    },
    {
      name: "Bruno Fernandes",
      cod: "POR-12",
      hasSticker: 0,
      image: require("../../assets/db/POR-12.jpg"),
    },
    {
      name: "Danilo Pereira",
      cod: "POR-13",
      hasSticker: 0,
      image: require("../../assets/db/POR-13.jpg"),
    },
    {
      name: "João Moutinho",
      cod: "POR-14",
      hasSticker: 0,
      image: require("../../assets/db/POR-14.jpg"),
    },
    {
      name: "Renato Sanches",
      cod: "POR-15",
      hasSticker: 0,
      image: require("../../assets/db/POR-15.jpg"),
    },
    {
      name: "Rúben Neves",
      cod: "POR-16",
      hasSticker: 0,
      image: require("../../assets/db/POR-16.jpg"),
    },
    {
      name: "André Silva ",
      cod: "POR-17",
      hasSticker: 0,
      image: require("../../assets/db/POR-17.jpg"),
    },
    {
      name: "Cristiano Ronaldo",
      cod: "POR-18",
      hasSticker: 0,
      image: require("../../assets/db/POR-18.jpg"),
    },
    {
      name: "Diogo Jota",
      cod: "POR-19",
      hasSticker: 0,
      image: require("../../assets/db/POR-19.jpg"),
    },
    {
      name: "Gonçalo Guedes",
      cod: "POR-20",
      hasSticker: 0,
      image: require("../../assets/db/POR-20.jpg"),
    },
    {
      name: "Squad",
      cod: "SEN-1",
      hasSticker: 0,
      image: require("../../assets/db/SEN-1.jpg"),
    },
    {
      name: "Logo",
      cod: "SEN-2",
      hasSticker: 0,
      image: require("../../assets/db/SEN-2.jpg"),
    },
    {
      name: "Édouard Mendy",
      cod: "SEN-3",
      hasSticker: 0,
      image: require("../../assets/db/SEN-3.jpg"),
    },
    {
      name: "Alfred Gomis",
      cod: "SEN-4",
      hasSticker: 0,
      image: require("../../assets/db/SEN-4.jpg"),
    },
    {
      name: "Saliou Ciss",
      cod: "SEN-5",
      hasSticker: 0,
      image: require("../../assets/db/SEN-5.jpg"),
    },
    {
      name: "Pape Abou Cissé",
      cod: "SEN-6",
      hasSticker: 0,
      image: require("../../assets/db/SEN-6.jpg"),
    },
    {
      name: "Abdou Diallo",
      cod: "SEN-7",
      hasSticker: 0,
      image: require("../../assets/db/SEN-7.jpg"),
    },
    {
      name: "Kalidou Koulibaly",
      cod: "SEN-8",
      hasSticker: 0,
      image: require("../../assets/db/SEN-8.jpg"),
    },
    {
      name: "Ibrahima Mbaye",
      cod: "SEN-9",
      hasSticker: 0,
      image: require("../../assets/db/SEN-9.jpg"),
    },
    {
      name: "Bouna Sarr",
      cod: "SEN-10",
      hasSticker: 0,
      image: require("../../assets/db/SEN-10.jpg"),
    },
    {
      name: "Krépin Diatta",
      cod: "SEN-11",
      hasSticker: 0,
      image: require("../../assets/db/SEN-11.jpg"),
    },
    {
      name: "Idrissa Gueye",
      cod: "SEN-12",
      hasSticker: 0,
      image: require("../../assets/db/SEN-12.jpg"),
    },
    {
      name: "Pape Gueye",
      cod: "SEN-13",
      hasSticker: 0,
      image: require("../../assets/db/SEN-13.jpg"),
    },
    {
      name: "Cheikhou Kouyaté",
      cod: "SEN-14",
      hasSticker: 0,
      image: require("../../assets/db/SEN-14.jpg"),
    },
    {
      name: "Nampalys Mendy",
      cod: "SEN-15",
      hasSticker: 0,
      image: require("../../assets/db/SEN-15.jpg"),
    },
    {
      name: "Boulaye Dia",
      cod: "SEN-16",
      hasSticker: 0,
      image: require("../../assets/db/SEN-16.jpg"),
    },
    {
      name: "Famara Diédhiou ",
      cod: "SEN-17",
      hasSticker: 0,
      image: require("../../assets/db/SEN-17.jpg"),
    },
    {
      name: "Bamba Dieng",
      cod: "SEN-18",
      hasSticker: 0,
      image: require("../../assets/db/SEN-18.jpg"),
    },
    {
      name: "Sadio Mané",
      cod: "SEN-19",
      hasSticker: 0,
      image: require("../../assets/db/SEN-19.jpg"),
    },
    {
      name: "Ismaïla Sarr",
      cod: "SEN-20",
      hasSticker: 0,
      image: require("../../assets/db/SEN-20.jpg"),
    },
  ];

  return data;
}
